stages:
  - test
  - acceptance

test_job:
  stage: test
  image: node:4.4.5
  script:
    - mkdir ~/.ssh/
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - git clone git@github.com:honest-code/Cart-checkout-BDD.git
    - cd Cart-checkout-BDD && npm install
    - npm update
    - npm prune
    - npm run test
    - npm run jshint
  cache:
    paths:
    - node_modules/
  only:
    - master

acceptance_job:
  stage: acceptance
  image: node:4.4.5
  script:
    - npm install
    - npm update
    - npm prune
    - screen -d -m -L npm start
    - npm run test-acceptance
    - npm run test-acceptance-file
  after_script:
    - npm run honestcode
  cache:
    paths:
    - node_modules/
  only:
    - master




