stages:
  - test
  - acceptance

image: node:4.4.5

variables: 
  REPO_URL: https://github.com/honest-code/Cart-checkout-BDD.git

test_job:
  stage: test
  script:
    - git clone $REPO_URL
    - cd Cart-checkout-BDD 
    - npm install
    - npm update
    - npm prune
    - npm run test
    - npm run jshint
  cache:
    paths:
    - node_modules/
  only:
    - master

acceptance_job:
  stage: acceptance
  script:
    - git clone $REPO_URL
    - cd Cart-checkout-BDD 
    - npm install
    - npm update
    - npm prune
    - screen -d -m -L npm start
    - npm run test-acceptance
    - npm run test-acceptance-file
  after_script:
    - npm run honestcode
  cache:
    paths:
    - node_modules/
  only:
    - master




