# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

  @tagF1
Feature: Feature 1
  as user
  I want to have the feature 1

  Background: background 1
    Given given 1
      | col 1  | col 2  |
      | 1____1 | 2____1 |
      | 1____2 | 2____2 |
      | 1____3 | 2____3 |
    And given 2
    And given 3

@tagOne
  Scenario: scenario 1
    Given given 1
      | col 1 | col 2 |
      | 1_1   | 2_1   |
      | 1_2   | 2_2   |
      | 1_3   | 2_3   |
    And given 2
    When when 1
    And when 2
    Then then 1
    And then 2
    And then 3

@tagTwo @tagThree
  Scenario Outline: scenario 2
    Given given 1
    When when 1
    Then then 1

    Examples:
      | col 1 | col 2 |
      | 1_1   | 2_1   |
      | 1_2   | 2_2   |
      | 1_3   | 2_3   |

  Scenario: scenario 3
