# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Special offers
      As a seller
      I want to be able to make special offers

  Scenario: Add items with promotion code 2x1
    Given a new checkout with code "1"
    And the product "Vino" price is 10
    And the product "Aceite" price is 6
    When I add a product with name "Vino"
    And I add a product with name "Vino"
    And I add a promotion with code "2x1"
    And I add a product with name "Aceite"
    Then the checkout has "16 EUR" in the total value

  Scenario: Add items without promotion code
    Given a new checkout with code "1"
    And the product "Vino" price is 12
    And the product "Aceite" price is 6
    When I add a product with name "Aceite"
    And I add a product with name "Vino"
    And I add a product with name "Vino"
    Then the checkout has "30 EUR" in the total value
